export { Dashboard } from './dashboard'
export { Chat } from './chat'
export { Orders } from './orders'
export { Products } from './products'
export { Customers } from './customers'
export { Campaigns } from './campaigns'
export { Transactions } from './transactions'
export { Wallet } from './wallet'
export { SingleCustomer } from './single-customer'
export { AddOrder } from './add-order'
export { AddProduct } from './add-product'
export { EditOrder } from './edit-order'
export { SingleOrder } from './single-order'
export { CreateTemplate } from './create-template'
export { default as Settings } from './settings'
